final List<Map<String, String>> projects = [
  {
    'title': 'WALL GALLERY',
    'description': 'Displays live weather data using OpenWeatherMap API.',
    'image': 'images/wall-gallery.jpeg',
    'link': 'https://github.com/Furqan-shah-furqan/wall-gallery.git',
  },
  {
    'title': 'Weather App',
    'description': 'Displays live weather data using OpenWeatherMap API.',
    'image': 'images/weather-api.png',
    'link': 'https://github.com/yourusername/weather_app',
  },
  {
    'title': 'To-Do List',
    'description': 'Organize daily tasks in a minimal to-do list UI.',
    'image': 'images/todo-app.png',
    'link': 'https://github.com/Furqan-shah-furqan/todo-app.git',
  },
  {
    'title': 'INSTA UI',
    'description': 'Instagram-inspired UI clone using Flutter widgets.',
    'image': 'images/insta_ui.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/insta_ui.git',
  },
  {
    'title': 'CRUD App',
    'description': 'Create, read, update, delete records in Flutter.',
    'image': 'images/crud.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/crud_flutter.git',
  },
  {
    'title': 'Light & Dark Theme',
    'description': 'Toggle between light and dark mode in Flutter.',
    'image': 'images/light-dark-theme.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/light-dark-theme.git',
  },
  {
    'title': 'Image Picker',
    'description': 'Pick images from gallery or camera in Flutter.',
    'image': 'images/image-picker.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/image-picker.git',
  },
  {
    'title': 'Juice Era UI',
    'description': 'A refreshing juice ordering UI made with Flutter.',
    'image': 'images/juice-era-drin.webp',
    'link': 'https://github.com/Furqan-shah-furqan/juice_era_drin.git',
  },
  {
    'title': 'Shoe Store',
    'description': 'E-commerce UI for browsing and buying shoes.',
    'image': 'images/shoe-store.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/shoe-store.git',
  },
  {
    'title': 'Audio Player UI',
    'description': 'Modern audio player interface with Flutter.',
    'image': 'images/audio-player1.png',
    'link': 'https://github.com/Furqan-shah-furqan/audio-player-modren-ui.git',
  },
  {
    'title': 'Calculator App',
    'description': 'Basic calculator with theme support.',
    'image': 'images/calculator.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/calculator-with-theme.git',
  },
  {
    'title': 'Layout Builder Demo',
    'description': 'Responsive UI using Flutter LayoutBuilder.',
    'image': 'images/layout-builder.png',
    'link': 'https://github.com/Furqan-shah-furqan/layout-builder.git',
  },
  {
    'title': 'Add to Cart',
    'description': 'Add-to-cart functionality in a shopping UI.',
    'image': 'images/add-to-cart.png',
    'link': 'https://github.com/Furqan-shah-furqan/add-to-cart.git',
  },
  {
    'title': 'Firebase Auth',
    'description': 'User authentication using Firebase in Flutter.',
    'image': 'images/firebase-auth.png',
    'link': 'https://github.com/Furqan-shah-furqan/firebase-auth.git',
  },
  {
    'title': 'Firebase CRUD',
    'description': 'CRUD operations with Firebase backend.',
    'image': 'images/firebase-crud.png',
    'link': 'https://github.com/Furqan-shah-furqan/firebase_crud.git',
  },
  {
    'title': 'WhatsApp UI',
    'description': 'WhatsApp-style UI built with Flutter widgets.',
    'image': 'images/whatsapp-ui.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/whatsapp_ui.git',
  },
  {
    'title': 'Music Player',
    'description': 'A beautiful and modern music player app.',
    'image': 'images/my-player.jpg',
    'link': 'https://github.com/Furqan-shah-furqan/my-player.git',
  },
];
